# http://module-build.sourceforge.net/META-spec.html
#
name:         Text-Phonetic-Nysiis
version:      1.0
version_from: Nysiis.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
